hc/urls.py
from django.urls import path
from hc.views.views_doctor import treatPatientView, patientHistoryView, load_users
from hc.views.views_patient import (
    makeAppointment, viewMedicalHistory, CreateProfileView,
    updateProfileView, AddFamilyMemberView
)
from hc.views.views_receptionist import SearchAppointmentView
from hc.views.views_pharmacist import ViewPrescription


app_name = 'hc'

urlpatterns = [
    path('treatPatient/', treatPatientView.as_view(template_name="doctor/treat_patient.html"),
         name='prescription'),
    path('makeAppointment/', makeAppointment, name='makeAppointment'),
    path('create_profile/', CreateProfileView.as_view(), name='createProfile'),
    path('update_profile/', updateProfileView, name='updateProfile'),
    path('add_member/', AddFamilyMemberView, name='add_member'),
    path('history/', viewMedicalHistory.as_view(), name='history'),
    path('<str:username>/history/', patientHistoryView.as_view(), name='patient'),
    path('<str:username>/appointment/', SearchAppointmentView, name='appointment'),  # receptionist
    path('<str:username>/prescription/', ViewPrescription, name='view_prescription'),  # pharmacist

    path('ajax/load_users/', load_users, name='ajax_load_users'),  # ajax load users(family members) from email id of ward

]

main/urls.py
from django.urls import path, include
from django.conf.urls import url
from .views import IndexView
from main.views import BlogDetailsView, AddBlogView, DevelopersPage, EditBlogView
from hc.views.views_receptionist import IndexViewReceptionist
from hc.views.views_pharmacist import IndexViewPharmacist
from hc.views.views_doctor import IndexViewDoctor

app_name = 'main'

urlpatterns = [
    path('', IndexView, name='home'),
    path('doctor/', IndexViewDoctor, name='home_doctor'),
    path('receptionist/', IndexViewReceptionist, name='home_receptionist'),
    path('pharmacist/', IndexViewPharmacist, name='home_pharmacist'),
    url(r'^blogs/(?P<slug>[\w-]+)/$', BlogDetailsView.as_view(), name='blog_details'),
    url(r'^blogs/edit/(?P<slug>[\w-]+)/$', EditBlogView, name='edit_blog'),
    path('addblog/', AddBlogView.as_view(), name='AddBlog'),
    path('developers/', DevelopersPage, name='developers'),
    path('hitcount/', include(('hitcount.urls', 'hitcount'), namespace='hitcount')),

]

website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('accounts.urls')),
    path('auth/', include('allauth.urls')),
    path('hc/', include('hc.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls'))
]

urlpatterns += static(settings.STATIC_URL,
                      document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

hc/forms/forms_doctor.py
from django import forms
from hc.models import Prescription
from accounts.models import Patient


class treatPatientForm(forms.ModelForm):

    class Meta:
        model = Prescription
        fields = ['remarks']


class SearchPatientForm(forms.Form):

    email = forms.EmailField(label="Email")
    username = forms.ChoiceField(label="Patient's Username")

    def __init__(self, *args, **kwargs):
        super(SearchPatientForm, self).__init__(*args, **kwargs)
        self.fields['username'].queryset = Patient.objects.none()

templates/pharmacist/index.html
{% extends 'doctor/base.html' %}
{% block body_block %}
{% load bootstrap4 %}
{% load static %}


<div class="homepage-boxes">
    <div class="container">
        <div class="row">
            <div class="col-12 col-md-6 col-lg-5 mt-5 mt-lg-0">
                <div class="appointment-box">
                    <h2 class="d-flex align-items-center">Prescription</h2>
                    <p></p>

                    <form method="POST" id="SearchPatientForm" action="{% url 'main:home_pharmacist' %}" data-users-url="{% url 'hc:ajax_load_users' %}" novalidate>
                        {% csrf_token %}
                        {% bootstrap_form form %}
                        <a href="{% url 'main:home_pharmacist' %}"><button class="button bg" type="submit">View Prescription</button></a>
                    </form>

                    <!-- creating AJAX request using jquery for dependant dropdown list of users having same email -->
                    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
                    <script>
                        $("#id_email").change(function () {
                        var url = $("#SearchPatientForm").attr("data-users-url");  // get the url of the `load_users` view
                        var EmailId = $(this).val();  // get the selected email ID of patient from the HTML input

                            $.ajax({                       // initialize an AJAX request
                                url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
                                data: {
                                'user_email': EmailId       // add the email id to the GET parameters
                                },
                                success: function (data) {   // `data` is the return of the `load_cities` view function
                                $("#id_username").html(data);  // replace the contents of the city input with the data that came from the server
                                }
                            });

                        });
                    </script>
                    <!-- jquery  -->
                </div>
            </div>
        </div>
    </div>
</div>

</div>
{% endblock %}

templates/pharmacist/prescription.html
{% extends 'main/base_forms.html' %}
{% block body_block %}
{% load bootstrap4 %}
{% load static %}

<div class="limiter">
    <div class="container-login100">
        <div class="wrap-login100 p-l-55 p-r-55 p-t-65 p-b-50">
            <form class="login100-form validate-form" enctype="multipart/form-data" method="POST">
                <span class="login100-form-title p-b-33">
                    Prescription
                </span>
                
                {% csrf_token %}
                {%  bootstrap_form form %}

                <div class="container-login100-form-btn m-t-20">
                    <button class="login100-form-btn">
                        Done
                    </button>
                </div>
                
            </form>
            <center><a href="{% url 'main:home' %}">Go Back</a></center>
        </div>
    </div>
</div>

{% endblock %}