accounts/urls.py
from django.contrib.auth import views as auth_views
from .views import CustomLoginView
from django.urls import path

app_name = 'accounts'

urlpatterns = [
    path('login/', CustomLoginView.as_view(template_name="accounts/login.html"), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='main:home'), name='logout'),
    # path('api/', include('accounts.api.urls'))
]

hc/urls.py
from django.urls import path
from hc.views.views_doctor import treatPatientView, patientHistoryView, load_users
from hc.views.views_patient import (
    makeAppointment, viewMedicalHistory, CreateProfileView,
    updateProfileView, AddFamilyMemberView
)
from hc.views.views_receptionist import SearchAppointmentView
from hc.views.views_pharmacist import ViewPrescription


app_name = 'hc'

urlpatterns = [
    path('treatPatient/', treatPatientView.as_view(template_name="doctor/treat_patient.html"),
         name='prescription'),
    path('makeAppointment/', makeAppointment, name='makeAppointment'),
    path('create_profile/', CreateProfileView.as_view(), name='createProfile'),
    path('update_profile/', updateProfileView, name='updateProfile'),
    path('add_member/', AddFamilyMemberView, name='add_member'),
    path('history/', viewMedicalHistory.as_view(), name='history'),
    path('<str:username>/history/', patientHistoryView.as_view(), name='patient'),
    path('<str:username>/appointment/', SearchAppointmentView, name='appointment'),  # receptionist
    path('<str:username>/prescription/', ViewPrescription, name='view_prescription'),  # pharmacist

    path('ajax/load_users/', load_users, name='ajax_load_users'),  # ajax load users(family members) from email id of ward

]

main/urls.py
from django.urls import path, include
from django.conf.urls import url
from .views import IndexView
from main.views import BlogDetailsView, AddBlogView, DevelopersPage, EditBlogView
from hc.views.views_receptionist import IndexViewReceptionist
from hc.views.views_pharmacist import IndexViewPharmacist
from hc.views.views_doctor import IndexViewDoctor

app_name = 'main'

urlpatterns = [
    path('', IndexView, name='home'),
    path('doctor/', IndexViewDoctor, name='home_doctor'),
    path('receptionist/', IndexViewReceptionist, name='home_receptionist'),
    path('pharmacist/', IndexViewPharmacist, name='home_pharmacist'),
    url(r'^blogs/(?P<slug>[\w-]+)/$', BlogDetailsView.as_view(), name='blog_details'),
    url(r'^blogs/edit/(?P<slug>[\w-]+)/$', EditBlogView, name='edit_blog'),
    path('addblog/', AddBlogView.as_view(), name='AddBlog'),
    path('developers/', DevelopersPage, name='developers'),
    path('hitcount/', include(('hitcount.urls', 'hitcount'), namespace='hitcount')),

]

website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('accounts.urls')),
    path('auth/', include('allauth.urls')),
    path('hc/', include('hc.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls'))
]

urlpatterns += static(settings.STATIC_URL,
                      document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from accounts.models import Doctor
from ckeditor_uploader.fields import RichTextUploadingField
from django.utils.text import slugify
from hitcount.models import HitCount
from django.contrib.contenttypes.fields import GenericRelation


class Blog(models.Model):
    title = models.CharField(max_length=250)
    author = models.ForeignKey(Doctor, on_delete=models.CASCADE)
    short_description = models.TextField()   # to be displayed on home page
    display_image = models.ImageField(
        upload_to='blog/',
        blank=True,
        null=True,
        default='blog/default.png',
        help_text='This image will be displayed on the home page of website')
    content = RichTextUploadingField()
    published_date = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(unique=True, blank=True)
    hit_count_generic = GenericRelation(HitCount, object_id_field='object_pk',
                                        related_query_name='hit_count_generic_relation')

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            if Blog.objects.filter(title=(self.title)).exists():
                count = Blog.objects.filter(title=(self.title)).count()
                self.slug = "%s-%s" % (slugify(kwargs.pop('title', self.title)), count+1)
            else:
                self.slug = slugify(kwargs.pop('title', self.title))
        return super(Blog, self).save(*args, **kwargs)

main/forms.py
from django import forms
from main.models import Blog


class AddBlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        exclude = ['author', 'slug']

main/views.py
from django.views.generic import CreateView
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import UserPassesTestMixin
from django.urls import reverse
from hitcount.views import HitCountDetailView
from accounts.models import Doctor, Patient
from hc.models import Appointment
from hc.forms.forms_patient import takeAppointmentForm
from main.forms import AddBlogForm
from hc.views.views_patient import makeAppointment
from main.models import Blog
import datetime as dt


def IndexView(request):
    args = {
        'blogs': Blog.objects.all(),
        'appn': None,
        'patientsInHc':
            len(Appointment.objects.filter(time__time__lte=(dt.datetime.now() + dt.timedelta(minutes=30)).time()))
    }

    if request.user.is_authenticated:
        if hasattr(request.user, 'doctor'):
            return redirect('main:home_doctor')
        elif hasattr(request.user, 'receptionist'):
            return redirect('main:home_receptionist')
        elif hasattr(request.user, 'pharmacist'):
            return redirect('main:home_pharmacist')
        args['appointments'] = Appointment.objects.all().filter(patient=request.user.username).order_by('time')
        if not hasattr(request.user, 'patient'):
            return redirect('hc:createProfile')
        args['staff'] = Patient.objects.get(user=request.user).staff

    if request.method == 'POST':
        return makeAppointment(request)

    args['form'] = takeAppointmentForm()
    return render(request, 'main/index.html', args)


class BlogDetailsView(HitCountDetailView):
    model = Blog
    template_name = 'main/blog_details.html'
    context_object_name = 'blog'
    slug_field = 'slug'
    count_hit = True

    def get_context_data(self, **kwargs):
        context = super(BlogDetailsView, self).get_context_data(**kwargs)
        return context

    def get_absolute_url(self):
        return reverse('main:blog_details', kwargs={'slug': self.slug})


class AddBlogView(SuccessMessageMixin, UserPassesTestMixin, CreateView):
    template_name = 'main/add_blog.html'
    form_class = AddBlogForm
    success_url = '/'
    extra_tags = 'd-flex justify-content-center alert alert-success alert-dismissible fade show'

    def test_func(self):
        return self.request.user.groups.filter(name='doctor').exists()

    def form_valid(self, form):
        form = form.save(commit=False)
        form.author = Doctor.objects.get(user=self.request.user)
        form.save()
        success_message = "Blog was successfully created."
        if success_message:
            messages.success(self.request, success_message, extra_tags=self.extra_tags)
        return redirect('main:home')


def EditBlogView(request, slug):
    blog = Blog.objects.filter(slug=slug)[0]
    form = AddBlogForm(instance=blog)
    if (request.method == "POST"):
        form = AddBlogForm(request.POST, instance=blog)
        form.save()
        return redirect('main:home')
    return render(request, 'main/edit_blog.html', {'form': form, 'blog': blog})


def DevelopersPage(request):
    return render(request, 'main/developers.html')

templates/main/add_blog.html
{% extends 'main/base_forms.html' %}
{% block body_block %}
{% load bootstrap4 %}

<div class="wrap-login100 p-l-55 p-r-55 p-t-65 p-b-50">
	<form class="login100-form validate-form" enctype="multipart/form-data" method="POST">
		<span class="login100-form-title p-b-33">
			Add Blog
		</span>
		{% csrf_token %}
		{{form.media}}
		{% bootstrap_form form %}

		<div class="container-login100-form-btn m-t-20">
			<button class="login100-form-btn">
				Add Blog
			</button>
		</div>
		<br>
	<center><a href="{% url 'main:home' %}">Go Back</a></center>
		
	</form>
</div>
{% endblock %}

templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <title>IIT Jodhpur - Hospital Management System</title>


  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

  <link rel="stylesheet" type="text/css"
    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


  <link rel="stylesheet" href="{% static 'css/swiper.min.css' %}">

  <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}" />

  <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>

<body onload="resizeElementHeight()"> 
  <div style="margin: 0;">
    {% if messages %}
    {% for message in messages %}
    <div {% if message.tags == "success" %} class="d-flex justify-content-center alert alert-success"
      {% elif message.tags %} class="{{ message.tags }}" {% else %}
      class="d-flex justify-content-center alert alert-secondary" {% endif %} style="margin: 0;">{{ message }}</div>
    {% endfor %}
    {% endif %}
  </div>
  <header class="site-header">
    <div class="nav-bar">
      <div class="container">
        <div class="row">
          <div class="col-12 d-flex flex-wrap justify-content-between align-items-center">
            <div class="site-branding d-flex align-items-center">

            </div>

            <nav class="site-navigation d-flex justify-content-end align-items-center">
              <ul class="d-flex flex-column flex-lg-row justify-content-lg-end align-items-center">
                <li class="menu-item"><a href="{% url 'main:home' %}">Home</a></li>
                {% if request.user.is_authenticated %}

                <li>
                  <div class="dropdown">
                    <button class="dropbtn">{{request.user.first_name}} <i class="fa fa-caret-down"></i></button>
                    <div class="dropdown-content">
                      <a href="{% url 'hc:updateProfile' %}">My Profile</a>
                      <a href="{% url 'hc:history' %}">History</a>
                      {% if staff %}
                        <a href="{% url 'hc:add_member' %}">Add Dependant</a>
                      {% endif %}
                      <a href="{% url 'accounts:logout' %}">Logout</a>
                    </div>
                  </div>
                </li>
                {% else %}

                <li><a href="/auth/google/login">Login</a></li>
                {% endif %}
                <li class="call-btn button bg mt-3 mt-md-0">
                  <a rel="" typography="LinkAlpha" data-ux="Link" href="tel:+912912801183"
                    class="d-flex justify-content-center align-items-center"
                    data-tccl="ux2.HEADER.header9.Section.Default.Link.Default.55282.click,click"><img
                      src="{% static 'images/emergency-call.png' %}">+91 291 280 1183</a>
                </li>
              </ul>
            </nav>

            <div class="hamburger-menu d-lg-none"><span></span><span></span><span></span><span></span></div>
          </div>
        </div>
      </div>
    </div>


  </header>
  {% block body_block %}
  {% endblock %}

  <footer class="footer">
    <div class="footer_content" >
      <div class="container">
        <div class="row footer_row">

          <div class="col-lg-4 footer_col">
            <div class="footer_item text-center">
              <div class="footer_title text-center">contact</div>
              <div class="footer_list">
                <ul>
                  <li><span>Phone:</span><a href="tel:+912912801183"> 291 280 1183</a></li>
                  <li><span>Email:</span><a href="mailto:hc@itj.ac.in"> hc@iitj.ac.in</a></li>
                </ul>
              </div>
            </div>
          </div>

          <div class="col-lg-4 footer_col">
            <div class="footer_item text-center">
              <div class="footer_title">useful links</div>
              <div class="footer_list">
                <ul>
                  <li><a target="_blank" href="https://docs.google.com/document/d/1i8Lie3fYyrLk6UYPV6UHJ602WPyiUyq9jcQnPUhubp4/edit?usp=sharing">Instructions</a></li>
                  <li><a href="/accounts/login">Staff Login</a></li>
                  <li><a href="{% url 'main:developers' %}">Developers</a></li>
                  <li><a href="/admin">Admin Portal</a></li>
                </ul>
              </div>
            </div>
          </div>

          <div class="col-lg-4 footer_col">
            <div class="footer_item text-center">
              <ul>
                <div class="footer_title text-center">
                  <h2><a href="http://iitj.ac.in/"><img src="{% static 'images/logo.png' %}" alt=""></a></h2>
                </div>
              </ul>
            </div>
          </div>

        </div>
      </div>
    </div>

    <!-- <div class="footer_bar d-flex flex-row align-items-center justify-content-center">
      <div class="copyright">
        Copyright &copy;
        <script>
          document.write(new Date().getFullYear());
        </script>
        All rights reserved
      </div>
    </div> -->

  </footer>
  



  <script type='text/javascript' src="{% static 'js/jquery.js' %}"></script>
  <script type='text/javascript' src="{% static 'js/jquery.collapsible.min.js' %}"></script>
  <script type='text/javascript' src="{% static 'js/swiper.min.js' %}"></script>
  <script type='text/javascript' src="{% static 'js/jquery.countTo.min.js' %}"></script>
  <script type='text/javascript' src="{% static 'js/jquery.barfiller.js' %}"></script>
  <script src="{% static 'js/custom.js' %}"></script>
  <!-- </div> -->
</body>
<script>
  function resizeElementHeight() {
    document.getElementsByClassName("hero-content-wrap")[0].style.minHeight = window.innerHeight.toString() + "px"
  }
</script>

</html>

templates/main/base_forms.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
	<title>IIT Jodhpur</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}" />
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
		integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

	<link rel="stylesheet" type="text/css" href="{% static 'css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/login_main.css' %}">

</head>

<body onload="resizeElementHeight()">
	<div class="limiter">
		<div class="container-login100">
			{% block body_block %}
			{% endblock %}
		</div>
	</div>



</body>
<script>
	function resizeElementHeight() {
		document.getElementsByClassName("container-login100")[0].style.backgroungheight = window.innerHeight.toString() +
			"px"
	}
</script>

</html>

templates/main/blog_details.html
{% extends 'main/base.html' %}
{% block body_block %}
{% load bootstrap4 %}
{% load static %}
{% load hitcount_tags %}

<div class="content" style="padding-top: 7%;">
    <div class="container">
        <div class="blog-wrap section-inner clearfix">
            <h1 class="blog-title">{{ blog.title|capfirst }}</h1>
            <div class="blog-info">
                <div class="posted-by">
                    <label>Author: </label>{{ blog.author.user.first_name|capfirst }} {{ blog.author.user.last_name|capfirst }} |
                                           {{ blog.published_date }} |
                    <label><i class="fa fa-eye"></i></label> {% get_hit_count for blog %}
                </div>
            </div> 
            <div class="blog-cover">
                <figure>
                    {% if blog.display_image %}
                    <img src= "{{ blog.display_image.url }}" alt="" height="230px">
                    {% endif %}
                </figure>
            </div>
            <div class="blog-content">
                {{ blog.content|safe }}
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/main/blogs_list.html
<div class="the-news">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <h2>
                    {% if attr == 'doctor' %}
                        My Blogs
                    {% else %}
                        The Blogs
                    {% endif %}
                </h2>
                <div class="row">
                    {% for blog in blogs %}
                    
                        <div class="col-12 col-md-6 col-lg-4">
                                <div class="the-news-wrap">
                                    {% if attr == 'doctor' %}
                                        <a href="{% url 'main:edit_blog' blog.slug %}" style="text-decoration: underline;">edit</a>
                                        <a href="{% url 'main:blog_details' blog.slug %}" style="text-decoration: underline;">view</a>
                                    {% endif %}
                                    <a href="{% url 'main:blog_details' blog.slug %}">
                                    <figure class="post-thumbnail">
                                            {% if blog.display_image %}
                                            <img src= "{{ blog.display_image.url }}" alt="" height="230px">
                                            {% endif %}
                                    </figure>
                                    <header class="entry-header">
                                        <h3 class="entry-title">{{ blog.title}}</h3>
                                        <div class="post-metas d-flex flex-wrap align-items-center">
                                            <div class="posted-date"><label>Date: </label>{{ blog.published_date}}</div>
                                            <div class="posted-by"><label>By: </label>{{ blog.author.user.first_name|capfirst }} {{ blog.author.user.last_name|capfirst }}</div>
                                            <!-- <div class="post-comments"><a href="#">2 Comments</a></div> -->
                                        </div>
                                    </header>
                                    <a href="{% url 'main:blog_details' blog.slug %}"><div class="entry-content">
                                        <p>{{ blog.short_description }}</p>
                                    </div></a>
                                </div>
                        </div>
                    </a>
                    {% endfor %}    
                </div>
            </div>
        </div>
    </div>
</div>

templates/main/developers.html
{% extends 'main/base.html' %}
{% block body_block %}
{% load bootstrap4 %}
{% load static %}


<!-- Section: Team v.1 -->
<section class="team-section text-center">

	<!-- Section heading -->
	<h2 class="h1-responsive font-weight-bold my-5"><u>THE TEAM</u></h2>
	<!-- Section description -->
		
	<div class="container">
		<!-- Grid row -->
		<div class="row">
			<!-- Grid column -->
			<div class="col-12 col-lg-12 col-md-12">
				<div class="avatar mx-auto">
				<img src="https://drive.google.com/thumbnail?id=1wbvoZ05hDfYO-cTNRxA33a-q-Ae4Fmlk" class="rounded-circle z-depth-1 d-flex justify-content-center"
					alt="Sample avatar">
				</div>
				<h5 class="font-weight-bold mt-2">Dr. Anand Mishra</h5>
				<p class="text-uppercase blue-text mt-2 mb-2">Mentor</p>
				<a class="fa fa-lg ins-ic" href="mailto:mishra@iitj.ac.in">
					<i class="fa fa-envelope blue-text"> mishra@iitj.ac.in</i>
				</a>
			</div>
			<!-- Grid column -->
		</div>
		<!-- Grid row -->

		<!-- Grid row -->
		<div class="row mt-4">
			<!-- Grid column -->
			<div class="col-12 col-md-6 col-lg-6">
				<div class="avatar mx-auto">
					<img src="https://drive.google.com/thumbnail?id=1prrgYu44J7-Ej0FA178_ltNwL7McCh1J" class="rounded-circle z-depth-1"
						alt="Sample avatar">
				</div>
				<h5 class="font-weight-bold mt-2">Harsh Anand</h5>
				<p class="text-uppercase blue-text mt-2 mb-2">Developer</p>
				<a class="fa fa-lg ins-ic" href="mailto:anand.2@iitj.ac.in">
					<i class="fa fa-envelope"> anand.2@iitj.ac.in </i>
				</a>
			</div>
			<!-- Grid column -->
		
			<!-- Grid column -->
			<div class="col-12 col-md-6 col-lg-6">
				<div class="avatar mx-auto">
				<img src="https://drive.google.com/thumbnail?id=18pmN6RazCqYODjZHu5m4DGopXOjYpKNB" class="rounded-circle z-depth-1 "
					alt="Sample avatar">
				</div>
				<h5 class="font-weight-bold mt-2">Yashvi Ramanuj</h5>
				<p class="text-uppercase blue-text mt-2 mb-2">Developer</p>
				<a class="p-2 fa fa-lg ins-ic" href="mailto:yashvi.1@iitj.ac.in">
					<i class="fa fa-envelope blue-text"> yashvi.1@iitj.ac.in </i>
				</a>
			</div>
			<!-- Grid column -->
		</div>
		<!-- Grid row -->


		<h4 class="h4-responsive font-weight-bold mb-5 pt-5 text-uppercase"><u>Special Thanks</u></h4>
		<!-- Grid row -->
		<div class="row">
			<!-- Grid column -->
			<div class="col-12 col-lg-4 col-md-6">
				<h5 class="font-weight-bold mt-4 mb-3">Anshul Ahuja</h5>
				<a class="p-2 fa fa-lg ins-ic" href="mailto:ahuja.2@iitj.ac.in">
					<i class="fa fa-envelope blue-text mb-3"> ahuja.2@iitj.ac.in</i>
				</a>
			</div>
			<!-- Grid column -->

			<!-- Grid column -->
			<div class="col-12 col-lg-4 col-md-6">
				<h5 class="font-weight-bold mt-4 mb-3">Soham Sonawane</h5>
				<a class="p-2 fa fa-lg ins-ic" href="mailto:sonawane.1@iitj.ac.in">
					<i class="fa fa-envelope blue-text mb-3"> sonawane.1@iitj.ac.in</i>
				</a>
			</div>
			<!-- Grid column -->

			<!-- Grid column -->
			<div class="col-12 col-lg-4 col-md-6">
				<h5 class="font-weight-bold mt-4 mb-3">Dheerendra Kumar Yadav</h5>
				<a class="p-2 fa fa-lg ins-ic" href="mailto:dk@iitj.ac.in">
					<i class="fa fa-envelope blue-text mb-3"> dk@iitj.ac.in</i>
				</a>
			</div>
			<!-- Grid column -->

			<!-- Grid row -->
		</div>
	</div>
		
	
</section>
{% endblock %}

templates/main/edit_blog.html
{% extends 'main/base_forms.html' %}
{% block body_block %}
{% load bootstrap4 %}

	<!-- <div class="limiter"> -->
		<!-- <div class="container-login100"> -->
			<div class="wrap-login100 p-l-55 p-r-55 p-t-65 p-b-50">
				<form class="login100-form validate-form" enctype="multipart/form-data" method="POST" action="{% url 'main:edit_blog' slug=blog.slug %}">
					<span class="login100-form-title p-b-33">
						Edit Blog
					</span>
					{% csrf_token %}
					{{form.media}}
					{% bootstrap_form form %}

					<div class="container-login100-form-btn m-t-20">
						<a href="{% url 'main:edit_blog' blog.slug %}"><button class="login100-form-btn">
							Edit Blog
						</button></a>
					</div>
					
				</form>
			</div>
		<!-- </div> -->
	<!-- </div> -->

{% endblock %}

templates/main/index.html
{% extends 'main/base.html' %}
{% block body_block %}
{% load crispy_forms_tags %}
{% load static %}


<div class="swiper-container hero-slider">
    <div ></div>
    <div class="swiper-wrapper">
        <div class="swiper-slide hero-content-wrap" style="background-image: url({% static 'images/background.jpg' %});">

            <div class="hero-content-overlay position-absolute w-100 h-100">

                <div class="container h-100">

                    <div class="row h-100">
                        <div class="col-12 col-lg-6 d-flex flex-column justify-content-center align-items-start">
                            <header class="entry-header">
                                <h1>Health Center<br>IIT Jodhpur</h1>
                            </header>
                            <footer class="entry-footer d-flex flex-wrap align-items-center mt-4">
                                <a href="http://iitj.ac.in/events/index.php?id=186&title=186&event=latest@iit_jodhpur"
                                    class="button bg">Read More</a>
                            </footer>
                        </div>
                    </div>
                </div>


            </div>
        </div>
    </div>
</div>
</div>
<div class="homepage-boxes">
    <div class="container">
        <div class="row">
            <div class="col-12 col-md-6 col-lg-4">
                <div class="opening-hours">
                    <h2 class="d-flex align-items-center">My Appointments</h2>
                    {% if not request.user.is_authenticated %}
                    <ul class="p-0 m-0">
                        <li>Log in to view Appointments.</li>
                    </ul>
                    {% elif appointments.count == 0 %}
                    <ul class="p-0 m-0">
                        <li>No Appointments!</li>
                    </ul>
                    {% else %}
                    <ul class="p-0 m-0">
                        {% for appointment in appointments %}
                        <li>Dr. {{appointment.doctor.user.first_name}} <span>{{appointment.time}}</span></li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                </div>
            </div>

            <div class="col-12 col-md-6 col-lg-3 mt-5 mt-md-0">
                <div class="emergency-box">
                    <h2 class="d-flex align-items-center">Emergency</h2>

                    <div class="call-btn button bg">
                        <a rel="" typography="LinkAlpha" data-ux="Link" href="tel:+912912801183"
                            class="d-flex justify-content-center align-items-center"
                            data-tccl="ux2.HEADER.header9.Section.Default.Link.Default.55282.click,click"><img
                                src="{% static 'images/emergency-call.png' %}">+91 291 280 1183</a>
                    </div>

                </div>
            </div>

            <div class="col-12 col-md-6 col-lg-5 mt-5 mt-lg-0">
                <div class="appointment-box">
                    <h2 class="d-flex align-items-center">Make an Appointment</h2>
                    <form method="POST">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <br>  
                        <button class="button bg" type="submit">Make Appointment</button>
                    </form>
                    <div class="pull-right"><p style="font-size: small;padding-top: 5px;">~ {{patientsInHc}} people expected in Health Center currently</p></div>
                    <br>
                </div>
            </div>
        </div>
    </div>
</div>


<section class="testimonial-section">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <h2>Facilities</h2>
            </div>
        </div>
    </div>


    <div class="testimonial-slider">
        <div class="container">
            <div class="row">
                <div class="col-12 col-lg-9">
                    <div class="testimonial-bg-shape">
                        <div class="swiper-container testimonial-slider-wrap">
                            <div class="swiper-wrapper">
                                <div class="swiper-slide">
                                    <div class="entry-content">
                                        A Primary Health Center (PHC) has been started at the Permanent Campus of
                                        IIT Jodhpur from 15 June 2017. This fully equipped and self-sufficient facility
                                        is run by M/s. Goyal Hospital & Research Center Private Limited, Jodhpur.
                                        The facility is available to the residents of the Permanent Campus in Karwar.
                                        Presently, the following facilities available at the PHC:<br>
                                        1. Qualified Medical Doctors and Paramedical Staff,<br>
                                        2. Physiotherapy Unit,<br>
                                        3. Pharmacy,<br>
                                        4. 24 Hours Emergency Room, and an ICU Ambulance.
                                    </div>
                                </div>


                                <div class="swiper-pagination-wrap">
                                    <div class="container">
                                        <div class="row">
                                            <div class="col-12">
                                                <div
                                                    class="swiper-pagination position-relative flex justify-content-center align-items-center">
                                                </div>
                                            </div><!-- .col -->
                                        </div><!-- .row -->
                                    </div><!-- .container -->
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
</section>

{% include 'main/blogs_list.html' with blogs=blogs %}


{% endblock %}