accounts/urls.py
from django.contrib.auth import views as auth_views
from .views import CustomLoginView
from django.urls import path

app_name = 'accounts'

urlpatterns = [
    path('login/', CustomLoginView.as_view(template_name="accounts/login.html"), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='main:home'), name='logout'),
    # path('api/', include('accounts.api.urls'))
]

hc/urls.py
from django.urls import path
from hc.views.views_doctor import treatPatientView, patientHistoryView, load_users
from hc.views.views_patient import (
    makeAppointment, viewMedicalHistory, CreateProfileView,
    updateProfileView, AddFamilyMemberView
)
from hc.views.views_receptionist import SearchAppointmentView
from hc.views.views_pharmacist import ViewPrescription


app_name = 'hc'

urlpatterns = [
    path('treatPatient/', treatPatientView.as_view(template_name="doctor/treat_patient.html"),
         name='prescription'),
    path('makeAppointment/', makeAppointment, name='makeAppointment'),
    path('create_profile/', CreateProfileView.as_view(), name='createProfile'),
    path('update_profile/', updateProfileView, name='updateProfile'),
    path('add_member/', AddFamilyMemberView, name='add_member'),
    path('history/', viewMedicalHistory.as_view(), name='history'),
    path('<str:username>/history/', patientHistoryView.as_view(), name='patient'),
    path('<str:username>/appointment/', SearchAppointmentView, name='appointment'),  # receptionist
    path('<str:username>/prescription/', ViewPrescription, name='view_prescription'),  # pharmacist

    path('ajax/load_users/', load_users, name='ajax_load_users'),  # ajax load users(family members) from email id of ward

]

main/urls.py
from django.urls import path, include
from django.conf.urls import url
from .views import IndexView
from main.views import BlogDetailsView, AddBlogView, DevelopersPage, EditBlogView
from hc.views.views_receptionist import IndexViewReceptionist
from hc.views.views_pharmacist import IndexViewPharmacist
from hc.views.views_doctor import IndexViewDoctor

app_name = 'main'

urlpatterns = [
    path('', IndexView, name='home'),
    path('doctor/', IndexViewDoctor, name='home_doctor'),
    path('receptionist/', IndexViewReceptionist, name='home_receptionist'),
    path('pharmacist/', IndexViewPharmacist, name='home_pharmacist'),
    url(r'^blogs/(?P<slug>[\w-]+)/$', BlogDetailsView.as_view(), name='blog_details'),
    url(r'^blogs/edit/(?P<slug>[\w-]+)/$', EditBlogView, name='edit_blog'),
    path('addblog/', AddBlogView.as_view(), name='AddBlog'),
    path('developers/', DevelopersPage, name='developers'),
    path('hitcount/', include(('hitcount.urls', 'hitcount'), namespace='hitcount')),

]

website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('accounts.urls')),
    path('auth/', include('allauth.urls')),
    path('hc/', include('hc.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls'))
]

urlpatterns += static(settings.STATIC_URL,
                      document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from hc.models import Prescription, DoctorSpecialization
from django.db.models.signals import post_save
from django.contrib.auth.models import Group


class Patient(models.Model):
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
        ('T', 'Transgender'),
    )
    BLOODGROUP_CHOICES = (
        ('NA', 'Don\'t Know'),
        ('O+', 'O Positive'),
        ('O-', 'O Negative'),
        ('A+', 'A Positive'),
        ('A-', 'A Negative'),
        ('B+', 'B Positive'),
        ('B-', 'B Negative'),
        ('AB+', 'AB Positive'),
        ('AB-', 'AB Negative'),
    )
    DISEASE_CHOICES = (
        ('1', 'Alzheimer’s'),
        ('2', 'Arthritis'),
        ('3', 'Asthma'),
        ('4', 'Blood Diseases'),
        ('5', 'Cancer'),
        ('6', 'Diabetes'),
        ('7', 'Heart Disease'),
        ('8', 'Hyper Tension'),
        ('9', 'Kidney Disease'),
        ('10', 'Liver Diseases'),
        ('11', 'Osteoporosis'),
        ('12', 'Pneumonia and Influenza'),
        ('13', 'Psychiatric Diseases'),
        ('14', 'Stroke and Cerebrovascular diseases'),
        ('15', 'Tuberculosis'),
    )

    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    num = models.CharField(max_length=15)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, default='M')
    birthday = models.DateField(auto_now=False)
    phone_number = models.CharField(max_length=12)
    emergency_phone = models.CharField(max_length=12)
    height = models.PositiveIntegerField()
    weight = models.PositiveIntegerField()
    blood_group = models.CharField(max_length=3, choices=BLOODGROUP_CHOICES, default='NA')
    past_diseases = models.CharField(max_length=2, choices=DISEASE_CHOICES, null=True, blank=True)
    other_diseases = models.CharField(max_length=20, default="nil")
    allergies = models.CharField(max_length=20, null=True, default="nil")
    prescriptions = models.ManyToManyField(Prescription, related_name="history", blank=True)
    staff = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username


def post_save_user(sender, instance, created, **kwargs):
    if created:
        instance.username = instance.email.split('@')[0]
        group = Group.objects.get(name="patient")
        instance.groups.add(group)
        instance.save()


post_save.connect(post_save_user, sender=User)


class Doctor(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    gender = models.CharField(max_length=1, choices=Patient.GENDER_CHOICES)
    specialization = models.ForeignKey(DoctorSpecialization, related_name="specializations",
                                       on_delete=models.SET_NULL, null=True)
    # shift_begin = models.TimeField(auto_now=False, auto_now_add=False)
    # shift_end = models.TimeField(auto_now=False, auto_now_add=False)
    available = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username


class Pharmacist(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.first_name + " " + self.user.last_name


class Receptionist(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.first_name + " " + self.user.last_name

hc/forms/forms_doctor.py
from django import forms
from hc.models import Prescription
from accounts.models import Patient


class treatPatientForm(forms.ModelForm):

    class Meta:
        model = Prescription
        fields = ['remarks']


class SearchPatientForm(forms.Form):

    email = forms.EmailField(label="Email")
    username = forms.ChoiceField(label="Patient's Username")

    def __init__(self, *args, **kwargs):
        super(SearchPatientForm, self).__init__(*args, **kwargs)
        self.fields['username'].queryset = Patient.objects.none()

templates/doctor/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <title>IIT Jodhpur</title>


  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

  <link rel="stylesheet" type="text/css"
    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


  <link rel="stylesheet" href="{% static 'css/swiper.min.css' %}">

  <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}" />

  <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>

<body onload="resizeElementHeight()"> 
  <div style="margin: 0;">
    {% if messages %}
    {% for message in messages %}
    <div {% if message.tags == "success" %} class="d-flex justify-content-center alert alert-success"
      {% elif message.tags %} class="{{ message.tags }}" {% else %}
      class="d-flex justify-content-center alert alert-secondary" {% endif %} style="margin: 0;">{{ message }}</div>
    {% endfor %}
    {% endif %}
  </div>
  <header class="site-header">
    <div class="nav-bar">
      <div class="container">
        <div class="row">
          <div class="col-12 d-flex flex-wrap justify-content-between align-items-center">
            <div class="site-branding d-flex align-items-center">

            </div>

            <nav class="site-navigation d-flex justify-content-end align-items-center">
              <ul class="d-flex flex-column flex-lg-row justify-content-lg-end align-items-center">
                <li class="current-menu-item"><a href="{% url 'main:home' %}">Home</a></li>
                {% if request.user.is_authenticated %}
                <li class="menu-item"><a href="{% url 'accounts:logout' %}">Logout</a></li>

                {% else %}

                <li><a href="/auth/google/login">Login</a></li>
                {% endif %}
                
              </ul>
            </nav>

            <div class="hamburger-menu d-lg-none"><span></span><span></span><span></span><span></span></div>
          </div>
        </div>
      </div>
    </div>


  </header>
  
  {% block body_block %}
  {% endblock %}

  <footer class="footer">
    <div class="footer_content" >
      <div class="container">
        <div class="row footer_row">

          <div class="col-lg-4 footer_col">
            <div class="footer_item text-center">
              <div class="footer_title text-center">contact</div>
              <div class="footer_list">
                <ul>
                  <li><span>Phone:</span><a href="tel:+912912801183"> 291 280 1183</a></li>
                  <li><span>Email:</span><a href="mailto:hc@itj.ac.in"> hc@iitj.ac.in</a></li>
                </ul>
              </div>
            </div>
          </div>

          <div class="col-lg-4 footer_col">
            <div class="footer_item text-center">
              <div class="footer_title">useful links</div>
              <div class="footer_list">
                <ul>
                  <li><a href="/">Home</a></li>
                  <li><a href="{% url 'main:developers' %}">Developers</a></li>
                  <li><a href="http://iitj.ac.in/events/index.php?id=186&title=186&event=latest@iit_jodhpur">About us</a></li>
                  <li><a href="/admin">Admin Portal</a></li>
                </ul>
              </div>
            </div>
          </div>

          <div class="col-lg-4 footer_col">
            <div class="footer_item text-center">
              <ul>
                <div class="footer_title text-center">
                  <h2><a href="http://iitj.ac.in/"><img src="{% static 'images/logo.png' %}" alt=""></a></h2>
                </div>
              </ul>
            </div>
          </div>

        </div>
      </div>
    </div>

    <!-- <div class="footer_bar d-flex flex-row align-items-center justify-content-center">
      <div class="copyright">
        Copyright &copy;
        <script>
          document.write(new Date().getFullYear());
        </script>
        All rights reserved
      </div>
    </div> -->

  </footer>
  



  <script type='text/javascript' src="{% static 'js/jquery.js' %}"></script>
  <script type='text/javascript' src="{% static 'js/jquery.collapsible.min.js' %}"></script>
  <script type='text/javascript' src="{% static 'js/swiper.min.js' %}"></script>
  <script type='text/javascript' src="{% static 'js/jquery.countTo.min.js' %}"></script>
  <script type='text/javascript' src="{% static 'js/jquery.barfiller.js' %}"></script>
  <script src="{% static 'js/custom.js' %}"></script>
  <!-- </div> -->
</body>
<script>
  function resizeElementHeight() {
    document.getElementsByClassName("hero-content-wrap")[0].style.minHeight = window.innerHeight.toString() + "px"
  }
</script>

</html>

templates/doctor/index.html
{% extends 'doctor/base.html' %}
{% block body_block %}
{% load bootstrap4 %}
{% load static %}
<div class="homepage-boxes">
    <div class="container">
        <div class="row">
            <div class="col-12 col-md-6 col-lg-4">
                <div class="appointment-box">
                    <h2 class="d-flex align-items-center">Next Patients</h2>
                    <p></p>

                    Treat the next patient in the queue.<br><br>
                    <a href="{% url 'hc:prescription' %}"><button class="button bg" type="submit">Treat
                        Patient</button></a>

                </div>
            </div>

            <div class="col-12 col-md-6 col-lg-5 mt-5 mt-lg-0">
                <div class="appointment-box">
                    <h2 class="d-flex align-items-center">Patients</h2>
                    <p></p>

                    <form method="POST" id="SearchPatientForm" action="{% url 'hc:prescription' %}" data-users-url="{% url 'hc:ajax_load_users' %}" novalidate>
                        {% csrf_token %}
                        {% bootstrap_form form %}
                        <a href="{% url 'hc:prescription' %}"><button class="button bg" type="submit">Treat
                            Patient</button></a>
                    </form>

                    <!-- creating AJAX request using jquery for dependant dropdown list of users having same email -->
                    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
                    <script>
                        $("#id_email").change(function () {
                        var url = $("#SearchPatientForm").attr("data-users-url");  // get the url of the `load_users` view
                        var EmailId = $(this).val();  // get the selected email ID of patient from the HTML input

                            $.ajax({                       // initialize an AJAX request
                                url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
                                data: {
                                'user_email': EmailId       // add the email id to the GET parameters
                                },
                                success: function (data) {   // `data` is the return of the `load_cities` view function
                                $("#id_username").html(data);  // replace the contents of the city input with the data that came from the server
                                }
                            });

                        });
                    </script>
                    <!-- jquery  -->

                </div>
            </div>
            <div class="col-12 col-md-6 col-lg-3 mt-5 mt-md-0">
                <div class="appointment-box">
                    <h2 class="d-flex align-items-center">Blogs</h2>
                    <p></p>
                    <a href="{% url 'main:AddBlog' %}"><button class="button bg" type="submit">Write a
                        Blog</button></a>
                </div>
            </div>

        </div>

        {% include 'main/blogs_list.html' with blogs=blogs attr='doctor' %}

    </div>
</div>

</div>
{% endblock %}

templates/doctor/patient_history.html
{% extends 'doctor/base.html' %}
{% load socialaccount %}
{% block body_block %}
{% load bootstrap4 %}
{% load static %}

<div style="padding-top: 30px;">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="services-tabs">
                    <div class="tabs">
                        
                        <div class="tabs-container">    
                            <div id="tab_1" class="tab-content">

                                <img src="{{ patient.user.socialaccount_set.all.0.get_avatar_url }}" height="330px">
                                <h4>{{patient.user.first_name}} {{patient.user.last_name}} ({{patient.gender}})</h4>
                                <div class="row">
                                    <p>Height: {{patient.height}} feet</p>
                                    <div style="padding-left: 50px;"></div>
                                    <p>Weight: {{patient.weight}} Kgs</p>
                                </div>
                                <p>Birthday: {{patient.birthday}}</p>

                                <p>Blood Group: {{patient.blood_group}}</p>
                                <p>Past Diseases: {{patient.get_past_diseases_display }}</p>
                                <p>Other Diseases: {{patient.other_diseases}}</p>
                                <p>Allergies: {{patient.allergies}}</p>
                                <p>Roll no. / PF no. : {{patient.num}}</p>
                                <div class="row">
                                    <p>Phone Number : {{patient.phone_number}}</p>
                                    <div style="padding-left: 50px;"></div>
                                    <p>Emergency Number : {{patient.emergency_phone}}</p>
                                </div>


                                <div>
                                    <br>
                                    <h4 class="d-flex justify-content-between align-items-center mb-12">
                                        <span class="text-muted">Medical History</span>
                                    </h4>
                                    <ul class="list-group mb-3">
                                        {% for prescription in prescriptions %}
                                        <li class="list-group-item d-flex justify-content-between lh-condensed">

                                            <div>
                                                <h6 class="my-0">Dr. {{prescription.doctor.user.first_name}}</h6>
                                                <small class="text-muted">{{prescription.remarks}}</small>
                                            </div>
                                            <span class="text-muted">ID: {{prescription.prescription_id}}</span>
                                        </li>
                                        {% endfor %}


                                    </ul>


                                </div>


                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>




        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
            integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        {% endblock %}

templates/doctor/treat_patient.html
{% extends 'main/base_forms.html' %}
{% block body_block %}
{% load bootstrap4 %}

<div class="limiter">
	{% if messages %}
	{% for message in messages %}
	<div {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</div>
	{% endfor %}
	{% endif %}
	<div class="container-login100">
		<div class="wrap-login100 p-l-55 p-r-55 p-t-65 p-b-50">
			 {% if appointment %} <a target="_blank"
						href="{% url 'hc:patient' username=patient.user.username %}">Patient: {{patient.user.first_name}}
						{{patient.user.last_name}}
				</a>
				{% if appointment.temp %}
					<div>Temp: {{appointment.temp}}</div>
				{% endif %}


				<form class="login100-form validate-form" enctype="multipart/form-data" method="POST">

					{% csrf_token %}

					{% bootstrap_form form %}

					<div class="container-login100-form-btn m-t-20">
						<button class="login100-form-btn">
							Submit
						</button>
					</div>
				</form>

				{% else %}
				<p>It seems that the patient has not taken the appointment</p>

				{% endif %}
				
				<br>
				<center><a href="{% url 'main:home' %}">Go Back</a></center>
			</div>
		</div>
	</div>

	{% endblock %}

templates/doctor/user_dropdown_options.html
<option value="">---------</option>
{% for user in users %}
<option value="{{ user.user.username }}">{{ user.user.first_name }} {{ user.user.last_name }}</option>
{% endfor %}